packages:
  - 'apps/*'
  - 'libs/core/*'
  - 'libs/modules/*'
  - 'libs/engines/*'
  - 'libs/modules/whatsapp/*'
autoInstallPeers: true
onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - 'esbuild'
  - 'less'
  - 'nx'
  - 'sharp'
  - 'unrs-resolver'
